apiVersion: v1
kind: Service
metadata:
  name: allans-fashion-blog-service
  labels:
    app: allans-fashion-blog
spec:
    type: NodePort
    selector:
        app: app
    ports:
     - protocol: TCP
       port: 30001
       targetPort: 30001
       nodePort: 30001
