apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app
spec:
    type: NodePort
    selector:
        app: app
    ports:
     - protocol: TCP
       port: 30000
       targetPort: 30000
       nodePort: 30000
