apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: allans-fashion-blog
spec:
  destination:
    name: ''
    namespace: kasper
    server: https://kubernetes.default.svc
  source:
    path: helm-tutorial/allans-fashion-blog/dreary-dwarf/helm
    repoURL: https://github.com/Kristoffer/argo-test.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
